version: "3.7"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.46.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    user: root
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus/
    - ./data/prometheus:/prometheus/
    restart: unless-stopped
    environment:
     - TZ="Asia/Yekaterinburg"

  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter:v0.24.0
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - 9115:9115
    restart: unless-stopped
    volumes:
      - ./blackbox:/config
  
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.25.0
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager/
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:10.0.3-ubuntu
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ="Asia/Yekaterinburg"